/* Bundle each Chrome execution world independently. No minification or dependencies. */
const fs=require('node:fs'),path=require('node:path');
const dir=path.resolve(__dirname,'../extension');
const read=file=>fs.readFileSync(path.join(dir,file),'utf8').replace(/\r\n/g,'\n');
const core=read('core.js').replace("if (typeof module === 'object' && module.exports) module.exports = api;\n  else root.XCountryCore = Object.freeze(api);","root.XCountryCore = Object.freeze(api);").replace('})(globalThis);','})(environment);');
const helpers=read('helpers.js').replace("const Core = typeof module === 'object' && module.exports ? require('./core.js') : root.XCountryCore;","const Core = root.XCountryCore;").replace("if(typeof module==='object' && module.exports) module.exports=api;else root.CleanXHelpers=Object.freeze(api);","root.CleanXHelpers=Object.freeze(api);").replace('})(globalThis);','})(environment);');
function write(file,parts) {
  fs.writeFileSync(path.join(dir,file),'/* Generated by scripts/build.cjs. Readable, self-contained browser bundle. */\n(() => {\n  const environment = {};\n'+parts.join('\n\n')+'\n})();\n');
}
write('page.js',[core,read('bridge.js').replaceAll('globalThis.XCountryCore','environment.XCountryCore')]);
write('cleanx.js',[core,helpers,read('content.js').replaceAll('globalThis.XCountryCore','environment.XCountryCore').replaceAll('globalThis.CleanXHelpers','environment.CleanXHelpers')]);
console.log('Built extension/page.js and extension/cleanx.js');
